// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow():Promise<void>;

export function GetURL():Promise<string>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;
